# Generated by Django 4.2.6 on 2023-10-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(max_length=63, verbose_name="Vorname")),
                ("input_url", models.URLField(max_length=511)),
            ],
        ),
    ]
