# Generated by Django 5.0.2 on 2024-06-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(
                        max_length=63, unique=True, verbose_name="Shop Name"
                    ),
                ),
                (
                    "input_url",
                    models.CharField(max_length=511, verbose_name="Feed URL"),
                ),
                (
                    "input_type",
                    models.CharField(max_length=63, verbose_name="Input Type"),
                ),
                (
                    "available_fields",
                    models.TextField(max_length=1023, verbose_name="Available Fields"),
                ),
                ("products_last_updated", models.DateTimeField()),
                ("products_update_cronjob_active", models.BooleanField()),
                ("auto_add_new_products_cronjob_active", models.BooleanField()),
                ("is_new_feed", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="FinalFeedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=63)),
                ("name", models.CharField(max_length=127)),
                ("short_desc", models.CharField(max_length=127)),
                ("long_description", models.CharField(max_length=2055)),
                (
                    "sales_price_excluding_tax",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("brand", models.CharField(max_length=63)),
                ("ean", models.CharField(max_length=63)),
                ("current_stock", models.CharField(max_length=63)),
                ("url_more_info", models.URLField(max_length=511)),
                ("shipmentby", models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name="FeedConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_schema_for_final_feed",
                    models.TextField(
                        max_length=1023, verbose_name="Product Schema For Final Field"
                    ),
                ),
                (
                    "custom_calculation_units_list",
                    models.TextField(
                        max_length=2055, verbose_name="Custom Calculation Units List"
                    ),
                ),
                (
                    "feed",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_feed_generator.feed",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_selected", models.BooleanField()),
                ("sku", models.CharField(max_length=65535)),
                ("name", models.CharField(max_length=65535)),
                ("short_desc", models.CharField(max_length=65535)),
                ("long_description", models.CharField(max_length=65535)),
                ("shipping_weight", models.CharField(max_length=65535)),
                ("main_image", models.CharField(max_length=65535)),
                ("extra_image_1", models.CharField(max_length=65535)),
                (
                    "sales_price_excluding_tax",
                    models.FloatField(blank=True, max_length=65535, null=True),
                ),
                ("brand", models.CharField(max_length=65535)),
                ("ean", models.CharField(max_length=65535)),
                ("current_stock", models.CharField(max_length=65535)),
                ("url_more_info", models.CharField(max_length=65535)),
                ("shipmentby", models.CharField(max_length=65535)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_feed_generator.feed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Imported Products",
            },
        ),
    ]
