# Generated by Django 4.2.6 on 2023-10-23 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0001_add_serverkast_product_and_feed_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Serverkast_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=63)),
                ("name", models.CharField(max_length=127)),
                ("short_desc", models.CharField(max_length=127)),
                ("long_description", models.CharField(max_length=2055)),
                ("gross_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("category", models.CharField(max_length=63)),
                ("brand", models.CharField(max_length=63)),
                ("ean", models.CharField(max_length=63)),
                ("current_stock", models.CharField(max_length=63)),
                ("url_more_info", models.URLField(max_length=511)),
                ("shipmentby", models.CharField(max_length=63)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_feed_generator.feed",
                    ),
                ),
            ],
        ),
    ]
