# Generated by Django 5.0.2 on 2024-05-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_feed_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedconfiguration",
            name="cost_price_multiplication_value",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedconfiguration",
            name="retail_price_excluding_tax_division_value",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedconfiguration",
            name="retail_price_excluding_tax_multiplication_value",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedconfiguration",
            name="sftp_url",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="feedconfiguration",
            name="xml_pass",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name="feedconfiguration",
            name="xml_user",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
