# Generated by Django 5.0.2 on 2024-05-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_feed_generator",
            "0002_feedconfiguration_cost_price_multiplication_value_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="cost_price_multiplication_value",
        ),
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="retail_price_excluding_tax_division_value",
        ),
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="retail_price_excluding_tax_multiplication_value",
        ),
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="sftp_url",
        ),
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="xml_pass",
        ),
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="xml_user",
        ),
    ]
