# Generated by Django 4.2.6 on 2023-10-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0003_add_checkbox_to_serverkast_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalFeedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=63)),
                ("name", models.CharField(max_length=127)),
                ("short_desc", models.CharField(max_length=127)),
                ("long_description", models.CharField(max_length=2055)),
                ("gross_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("brand", models.CharField(max_length=63)),
                ("ean", models.CharField(max_length=63)),
                ("current_stock", models.CharField(max_length=63)),
                ("url_more_info", models.URLField(max_length=511)),
                ("shipmentby", models.CharField(max_length=63)),
            ],
        ),
        migrations.RemoveField(
            model_name="serverkast_product",
            name="category",
        ),
        migrations.AddField(
            model_name="serverkast_product",
            name="extra_image_1",
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name="serverkast_product",
            name="extra_image_2",
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name="serverkast_product",
            name="extra_image_3",
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name="serverkast_product",
            name="extra_image_4",
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name="serverkast_product",
            name="extra_image_5",
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name="serverkast_product",
            name="extra_image_6",
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name="serverkast_product",
            name="extra_image_7",
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name="serverkast_product",
            name="extra_image_8",
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name="serverkast_product",
            name="extra_image_9",
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name="serverkast_product",
            name="main_image",
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
    ]
