# Generated by Django 5.0.2 on 2024-05-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_feed_generator",
            "0003_remove_feedconfiguration_cost_price_multiplication_value_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="feedconfiguration",
            name="sftp_url",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="feedconfiguration",
            name="xml_pass",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name="feedconfiguration",
            name="xml_user",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
