# Generated by Django 4.2.6 on 2023-11-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0004_add_image_to_serverkast_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopsyStemsProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_selected", models.BooleanField()),
                ("sku", models.CharField(max_length=63)),
                ("name", models.CharField(max_length=127)),
                ("short_desc", models.CharField(max_length=127)),
                ("long_description", models.CharField(max_length=2055)),
                ("main_image", models.URLField(blank=True, max_length=511, null=True)),
                (
                    "extra_image_1",
                    models.URLField(blank=True, max_length=511, null=True),
                ),
                (
                    "extra_image_2",
                    models.URLField(blank=True, max_length=511, null=True),
                ),
                (
                    "extra_image_3",
                    models.URLField(blank=True, max_length=511, null=True),
                ),
                (
                    "extra_image_4",
                    models.URLField(blank=True, max_length=511, null=True),
                ),
                (
                    "extra_image_5",
                    models.URLField(blank=True, max_length=511, null=True),
                ),
                (
                    "extra_image_6",
                    models.URLField(blank=True, max_length=511, null=True),
                ),
                (
                    "extra_image_7",
                    models.URLField(blank=True, max_length=511, null=True),
                ),
                (
                    "extra_image_8",
                    models.URLField(blank=True, max_length=511, null=True),
                ),
                (
                    "extra_image_9",
                    models.URLField(blank=True, max_length=511, null=True),
                ),
                ("gross_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("brand", models.CharField(max_length=63)),
                ("ean", models.CharField(max_length=63)),
                ("current_stock", models.CharField(max_length=63)),
                ("url_more_info", models.URLField(max_length=511)),
                ("shipmentby", models.CharField(max_length=63)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_feed_generator.feed",
                    ),
                ),
            ],
        ),
    ]
