# Generated by Django 5.0.2 on 2024-05-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_feed_generator", "0004_feedconfiguration_sftp_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="sftp_url",
        ),
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="xml_pass",
        ),
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="xml_user",
        ),
    ]
