# Generated by Django 5.0.2 on 2024-06-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_feed_generator", "0005_remove_feedconfiguration_sftp_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="input_url",
            field=models.CharField(max_length=511, verbose_name="XML URL"),
        ),
    ]
