# Generated by Django 4.2.6 on 2023-11-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0005_add_topsystems_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverkast_product",
            name="gross_price",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name="topsystemsproduct",
            name="gross_price",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
