# Generated by Django 5.0.2 on 2024-06-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_feed_generator", "0006_alter_feed_input_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name="product",
            name="current_stock",
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name="product",
            name="ean",
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name="product",
            name="extra_image_1",
            field=models.CharField(default="", max_length=65535),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.CharField(default="", max_length=65535),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="sales_price_excluding_tax",
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipmentby",
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_weight",
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                max_length=65535, verbose_name="MPN (originally SKU)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="url_more_info",
            field=models.CharField(max_length=65535),
        ),
    ]
