# Generated by Django 4.2.6 on 2023-11-05 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0006_add_topsystems_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topsystemsproduct",
            name="extra_image_2",
        ),
        migrations.RemoveField(
            model_name="topsystemsproduct",
            name="extra_image_3",
        ),
        migrations.RemoveField(
            model_name="topsystemsproduct",
            name="extra_image_4",
        ),
        migrations.RemoveField(
            model_name="topsystemsproduct",
            name="extra_image_5",
        ),
        migrations.RemoveField(
            model_name="topsystemsproduct",
            name="extra_image_6",
        ),
        migrations.RemoveField(
            model_name="topsystemsproduct",
            name="extra_image_7",
        ),
        migrations.RemoveField(
            model_name="topsystemsproduct",
            name="extra_image_8",
        ),
        migrations.RemoveField(
            model_name="topsystemsproduct",
            name="extra_image_9",
        ),
    ]
