# Generated by Django 5.0.2 on 2024-06-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_feed_generator",
            "0007_alter_product_brand_alter_product_current_stock_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="is_new_feed",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feed",
            name="input_url",
            field=models.CharField(max_length=511, verbose_name="Feed URL"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=65535),
        ),
    ]
