# Generated by Django 5.0.2 on 2024-06-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_feed_generator", "0009_alter_product_sales_price_excluding_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sales_price_excluding_tax",
            field=models.FloatField(blank=True, max_length=65535),
        ),
    ]
