# Generated by Django 4.2.6 on 2023-11-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0010_update_feed_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="products_update_cronjob_active",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
