# Generated by Django 4.2.6 on 2023-11-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0011_update_feed_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="products_last_updated",
            field=models.DateTimeField(),
        ),
    ]
