# Generated by Django 4.2.6 on 2023-11-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0012_update_feed_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division_value", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "multiplication_value",
                    models.DecimalField(decimal_places=2, max_digits=9),
                ),
                (
                    "feed",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_feed_generator.feed",
                    ),
                ),
            ],
        ),
    ]
