# Generated by Django 4.2.6 on 2023-11-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0013_create_feed_config"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedconfiguration",
            old_name="division_value",
            new_name="cost_price_multiplication_value",
        ),
        migrations.RenameField(
            model_name="feedconfiguration",
            old_name="multiplication_value",
            new_name="retail_price_excluding_tax_division_value",
        ),
        migrations.AddField(
            model_name="feedconfiguration",
            name="retail_price_excluding_tax_multiplication_value",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=9),
            preserve_default=False,
        ),
    ]
