# Generated by Django 4.2.6 on 2023-11-30 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0014_create_feed_config"),
    ]

    operations = [
        migrations.RenameField(
            model_name="serverkast_product",
            old_name="gross_price",
            new_name="sales_price_excluding_tax",
        ),
        migrations.RenameField(
            model_name="topsystemsproduct",
            old_name="gross_price",
            new_name="sales_price_excluding_tax",
        ),
    ]
