# Generated by Django 4.2.6 on 2023-12-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0016_change_name_of_gross_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="input_type",
            field=models.CharField(
                default="", max_length=63, verbose_name="Input Type"
            ),
            preserve_default=False,
        ),
    ]
