# Generated by Django 4.2.6 on 2023-12-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0018_add_fields_for_final_feed_to_feed_conf_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="original_fields_for_final_feed",
        ),
        migrations.AddField(
            model_name="feedconfiguration",
            name="custom_calculated_field_1",
            field=models.CharField(
                default="", max_length=1023, verbose_name="Custom Calculated Field 1"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedconfiguration",
            name="custom_calculated_field_2",
            field=models.CharField(
                default="", max_length=1023, verbose_name="Custom Calculated Field 2"
            ),
            preserve_default=False,
        ),
    ]
