# Generated by Django 4.2.6 on 2024-01-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0020_add_product_schema_field_to_conf_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngramMicroProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_selected", models.BooleanField()),
                ("ingram_part_number", models.CharField(max_length=63)),
                ("ingram_part_description", models.CharField(max_length=127)),
                ("long_description", models.CharField(max_length=2055)),
                ("brand", models.CharField(max_length=63)),
                ("ean", models.CharField(max_length=63)),
                ("current_stock", models.CharField(max_length=63)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_feed_generator.feed",
                    ),
                ),
            ],
        ),
    ]
