# Generated by Django 5.0.1 on 2024-01-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0021_add_imgram_micro_product_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingrammicroproduct",
            options={
                "verbose_name": "Ingram Micro Product",
                "verbose_name_plural": "Imported Ingram Micro Products",
            },
        ),
        migrations.AlterModelOptions(
            name="serverkast_product",
            options={
                "verbose_name": "Serverkast Product",
                "verbose_name_plural": "Imported Serverkast Products",
            },
        ),
        migrations.AlterModelOptions(
            name="topsystemsproduct",
            options={
                "verbose_name": "Top Systems Product",
                "verbose_name_plural": "Imported Top Systems Products",
            },
        ),
        migrations.AddField(
            model_name="feedconfiguration",
            name="sftp_url",
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="feedconfiguration",
            name="xml_pass",
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name="feedconfiguration",
            name="xml_user",
            field=models.CharField(max_length=63, null=True),
        ),
    ]
