# Generated by Django 5.0.1 on 2024-01-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_feed_generator", "0022_add_credentials_to_feed_conf_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedconfiguration",
            name="sftp_url",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="feedconfiguration",
            name="xml_pass",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name="feedconfiguration",
            name="xml_user",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
