# Generated by Django 5.0.1 on 2024-01-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_feed_generator", "0023_add_credentials_to_feed_conf_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedconfiguration",
            name="product_schema_for_final_feed",
            field=models.TextField(
                max_length=1023, verbose_name="Product Schema For Final Field"
            ),
        ),
    ]
