# Generated by Django 5.0.1 on 2024-02-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_feed_generator", "0024_add_json_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedconfiguration",
            old_name="custom_calculated_field_1",
            new_name="custom_calculation_units_list",
        ),
    ]
