# Generated by Django 5.0.1 on 2024-02-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_feed_generator", "0025_rename_custom_calculation_units_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="custom_calculated_field_2",
        ),
        migrations.AlterField(
            model_name="feedconfiguration",
            name="custom_calculation_units_list",
            field=models.TextField(
                max_length=1023, verbose_name="Custom Calculation Units List"
            ),
        ),
    ]
