# Generated by Django 5.0.1 on 2024-02-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_feed_generator", "0026_remove_custom_calculated_field_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedconfiguration",
            name="custom_calculation_units_list",
            field=models.TextField(
                max_length=2055, verbose_name="Custom Calculation Units List"
            ),
        ),
    ]
