# Generated by Django 5.0.1 on 2024-02-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_feed_generator", "0027_remove_custom_calculated_field_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="auto_add_new_products_cronjob_active",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
