# Generated by Django 5.0.2 on 2024-02-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_feed_generator",
            "0028_add_auto_add_new_products_boolean_to_feed_model",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverkast_product",
            name="long_description",
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name="serverkast_product",
            name="name",
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name="serverkast_product",
            name="short_desc",
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name="topsystemsproduct",
            name="long_description",
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name="topsystemsproduct",
            name="name",
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name="topsystemsproduct",
            name="short_desc",
            field=models.CharField(max_length=65535),
        ),
    ]
