# Generated by Django 5.0.2 on 2024-04-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_feed_generator",
            "0029_change_length_of_product_fields_for_bugfixing_postgres_migration",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_selected", models.BooleanField()),
                (
                    "sku",
                    models.CharField(
                        max_length=63, verbose_name="MPN (originally SKU)"
                    ),
                ),
                ("name", models.CharField(max_length=65535)),
                ("short_desc", models.CharField(max_length=65535)),
                ("long_description", models.CharField(max_length=65535)),
                (
                    "shipping_weight",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("main_image", models.URLField(blank=True, max_length=511, null=True)),
                (
                    "extra_image_1",
                    models.URLField(blank=True, max_length=511, null=True),
                ),
                (
                    "sales_price_excluding_tax",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name="Gross Price – calculated from original Price",
                    ),
                ),
                ("brand", models.CharField(max_length=63)),
                ("ean", models.CharField(max_length=63)),
                ("current_stock", models.CharField(max_length=63)),
                ("url_more_info", models.URLField(max_length=511)),
                ("shipmentby", models.CharField(max_length=63)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_feed_generator.feed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Imported Products",
            },
        ),
    ]
