# Generated by Django 5.0.1 on 2024-05-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_feed_generator', '0030_add_generic_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverkast_product',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='topsystemsproduct',
            name='feed',
        ),
        migrations.DeleteModel(
            name='IngramMicroProduct',
        ),
        migrations.DeleteModel(
            name='Serverkast_Product',
        ),
        migrations.DeleteModel(
            name='TopsyStemsProduct',
        ),
    ]
