# Generated by Django 5.0.2 on 2024-05-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_feed_generator", "0031_remove_serverkast_product_feed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="available_fields",
            field=models.CharField(
                default="", max_length=1023, verbose_name="Available Fields"
            ),
            preserve_default=False,
        ),
    ]
