# Generated by Django 5.0.2 on 2024-05-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_feed_generator", "0032_feed_available_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="available_fields",
            field=models.TextField(max_length=1023, verbose_name="Available Fields"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="shop_name",
            field=models.CharField(
                max_length=63, unique=True, verbose_name="Shop Name"
            ),
        ),
    ]
