# Generated by Django 5.0.2 on 2024-05-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_feed_generator",
            "0033_alter_feed_available_fields_alter_feed_shop_name",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="cost_price_multiplication_value",
        ),
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="retail_price_excluding_tax_division_value",
        ),
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="retail_price_excluding_tax_multiplication_value",
        ),
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="sftp_url",
        ),
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="xml_pass",
        ),
        migrations.RemoveField(
            model_name="feedconfiguration",
            name="xml_user",
        ),
    ]
